测速失败 http://pan.qiaoji8.com/tvbox/neibu.php?url=: HTTPSConnectionPool(host='jf.wsp2.cn', port=443): Max retries exceeded with url: /api/?key=82c93ab9d0b9e7ceeace5d9b1daa087c&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf01c0>, 'Connection to jf.wsp2.cn timed out. (connect timeout=5)'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf1570>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://yunhai.qijiyun.vip/home/api?type=ys&uid=177259&key=dijnouxKNOQSTUWXY5&url=: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
测速失败 http://yunhai.qijiyun.vip/home/api?type=ys&uid=177259&key=dijnouxKNOQSTUWXY5&url=: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
测速失败 http://yunhai.qijiyun.vip/home/api?type=ys&uid=177259&key=dijnouxKNOQSTUWXY5&url=: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf1fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf09d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://1.94.221.189:88/algorithm.php?url=: HTTPConnectionPool(host='1.94.221.189', port=88): Max retries exceeded with url: /algorithm.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://110.40.85.39:81/jxxx/api.php?url=: HTTPConnectionPool(host='110.40.85.39', port=81): Max retries exceeded with url: /jxxx/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf08b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://110.40.85.39:81/jxxx/api.php?url=: HTTPConnectionPool(host='110.40.85.39', port=81): Max retries exceeded with url: /jxxx/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf2c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://110.40.85.39:81/jxxx/api.php?url=: HTTPConnectionPool(host='110.40.85.39', port=81): Max retries exceeded with url: /jxxx/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf18d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://jx.zhanlangbu.com/?url=: HTTPSConnectionPool(host='jx.zhanlangbu.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0430>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://jx.zhanlangbu.com/?url=: HTTPSConnectionPool(host='jx.zhanlangbu.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0520>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://jx.zhanlangbu.com/?url=: HTTPSConnectionPool(host='jx.zhanlangbu.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf25c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://jx.jsonplayer.com/player/?url=: HTTPSConnectionPool(host='jx.jsonplayer.com', port=443): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0c10>: Failed to resolve 'jx.jsonplayer.com' ([Errno -2] Name or service not known)"))
测速失败 https://jx.jsonplayer.com/player/?url=: HTTPSConnectionPool(host='jx.jsonplayer.com', port=443): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2b30>: Failed to resolve 'jx.jsonplayer.com' ([Errno -2] Name or service not known)"))
测速失败 https://jx.jsonplayer.com/player/?url=: HTTPSConnectionPool(host='jx.jsonplayer.com', port=443): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5fbb0>: Failed to resolve 'jx.jsonplayer.com' ([Errno -2] Name or service not known)"))
测速失败 https://110.42.2.247:9090/player/?url=: HTTPSConnectionPool(host='110.42.2.247', port=9090): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf19f0>, 'Connection to 110.42.2.247 timed out. (connect timeout=5)'))
测速失败 https://110.42.2.247:9090/player/?url=: HTTPSConnectionPool(host='110.42.2.247', port=9090): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf22c0>, 'Connection to 110.42.2.247 timed out. (connect timeout=5)'))
测速失败 https://110.42.2.247:9090/player/?url=: HTTPSConnectionPool(host='110.42.2.247', port=9090): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2290>, 'Connection to 110.42.2.247 timed out. (connect timeout=5)'))
测速失败 http://112.74.124.75:8899/jiexi/api.php?url=: HTTPConnectionPool(host='112.74.124.75', port=8899): Max retries exceeded with url: /jiexi/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ebf2f80>, 'Connection to 112.74.124.75 timed out. (connect timeout=5)'))
测速失败 http://112.74.124.75:8899/jiexi/api.php?url=: HTTPConnectionPool(host='112.74.124.75', port=8899): Max retries exceeded with url: /jiexi/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0a30>, 'Connection to 112.74.124.75 timed out. (connect timeout=5)'))
测速失败 http://112.74.124.75:8899/jiexi/api.php?url=: HTTPConnectionPool(host='112.74.124.75', port=8899): Max retries exceeded with url: /jiexi/api.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ed5ca90>, 'Connection to 112.74.124.75 timed out. (connect timeout=5)'))
测速失败 http://localhost:5705/parse/api/哔哩.js?url=: HTTPConnectionPool(host='localhost', port=5705): Max retries exceeded with url: /parse/api/%E5%93%94%E5%93%A9.js?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf1450>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://localhost:5705/parse/api/哔哩.js?url=: HTTPConnectionPool(host='localhost', port=5705): Max retries exceeded with url: /parse/api/%E5%93%94%E5%93%A9.js?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf22f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://localhost:5705/parse/api/哔哩.js?url=: HTTPConnectionPool(host='localhost', port=5705): Max retries exceeded with url: /parse/api/%E5%93%94%E5%93%A9.js?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ebf2140>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 http://rxjx.kuanjv.com/allm3u8.php?url=: HTTPConnectionPool(host='rxjx.kuanjv.com', port=80): Max retries exceeded with url: /allm3u8.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf1600>: Failed to resolve 'rxjx.kuanjv.com' ([Errno -2] Name or service not known)"))
测速失败 http://rxjx.kuanjv.com/allm3u8.php?url=: HTTPConnectionPool(host='rxjx.kuanjv.com', port=80): Max retries exceeded with url: /allm3u8.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0eb0>: Failed to resolve 'rxjx.kuanjv.com' ([Errno -2] Name or service not known)"))
测速失败 http://rxjx.kuanjv.com/allm3u8.php?url=: HTTPConnectionPool(host='rxjx.kuanjv.com', port=80): Max retries exceeded with url: /allm3u8.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf2a70>: Failed to resolve 'rxjx.kuanjv.com' ([Errno -2] Name or service not known)"))
测速失败 http://jx.nikucms.com/pc/index6.php?url=: HTTPConnectionPool(host='jx.nikucms.com', port=80): Max retries exceeded with url: /pc/index6.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0190>: Failed to resolve 'jx.nikucms.com' ([Errno -5] No address associated with hostname)"))
测速失败 http://jx.nikucms.com/pc/index6.php?url=: HTTPConnectionPool(host='jx.nikucms.com', port=80): Max retries exceeded with url: /pc/index6.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf23b0>: Failed to resolve 'jx.nikucms.com' ([Errno -5] No address associated with hostname)"))
测速失败 http://jx.nikucms.com/pc/index6.php?url=: HTTPConnectionPool(host='jx.nikucms.com', port=80): Max retries exceeded with url: /pc/index6.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf12a0>: Failed to resolve 'jx.nikucms.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe220902&url=: HTTPSConnectionPool(host='play.fuqizhishi.com', port=443): Max retries exceeded with url: /juhe/API.php?appkey=caijijuhe220902&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1540>: Failed to resolve 'play.fuqizhishi.com' ([Errno -2] Name or service not known)"))
测速失败 https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe220902&url=: HTTPSConnectionPool(host='play.fuqizhishi.com', port=443): Max retries exceeded with url: /juhe/API.php?appkey=caijijuhe220902&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3610>: Failed to resolve 'play.fuqizhishi.com' ([Errno -2] Name or service not known)"))
测速失败 https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe220902&url=: HTTPSConnectionPool(host='play.fuqizhishi.com', port=443): Max retries exceeded with url: /juhe/API.php?appkey=caijijuhe220902&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0e50>: Failed to resolve 'play.fuqizhishi.com' ([Errno -2] Name or service not known)"))
测速失败 https://vip.cyu0.cn/home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=: HTTPSConnectionPool(host='vip.cyu0.cn', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf05b0>: Failed to resolve 'vip.cyu0.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://vip.cyu0.cn/home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=: HTTPSConnectionPool(host='vip.cyu0.cn', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf04f0>: Failed to resolve 'vip.cyu0.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://vip.cyu0.cn/home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=: HTTPSConnectionPool(host='vip.cyu0.cn', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1353484&key=efopqwABCLOTVYZ278&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5f280>: Failed to resolve 'vip.cyu0.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://okjx.cc/?url=: HTTPSConnectionPool(host='okjx.cc', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1f30>: Failed to resolve 'okjx.cc' ([Errno -5] No address associated with hostname)"))
测速失败 https://okjx.cc/?url=: HTTPSConnectionPool(host='okjx.cc', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2860>: Failed to resolve 'okjx.cc' ([Errno -5] No address associated with hostname)"))
测速失败 https://okjx.cc/?url=: HTTPSConnectionPool(host='okjx.cc', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1a80>: Failed to resolve 'okjx.cc' ([Errno -5] No address associated with hostname)"))
测速失败 https://svip.spchat.top/api/?key=O9HGeIVUqU3REsnmQP&url=: HTTPSConnectionPool(host='svip.spchat.top', port=443): Max retries exceeded with url: /api/?key=O9HGeIVUqU3REsnmQP&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0fd0>: Failed to resolve 'svip.spchat.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://svip.spchat.top/api/?key=O9HGeIVUqU3REsnmQP&url=: HTTPSConnectionPool(host='svip.spchat.top', port=443): Max retries exceeded with url: /api/?key=O9HGeIVUqU3REsnmQP&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3250>: Failed to resolve 'svip.spchat.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://svip.spchat.top/api/?key=O9HGeIVUqU3REsnmQP&url=: HTTPSConnectionPool(host='svip.spchat.top', port=443): Max retries exceeded with url: /api/?key=O9HGeIVUqU3REsnmQP&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5cdc0>: Failed to resolve 'svip.spchat.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://v.2080kk.com/home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=: HTTPSConnectionPool(host='v.2080kk.com', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf38b0>: Failed to resolve 'v.2080kk.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://v.2080kk.com/home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=: HTTPSConnectionPool(host='v.2080kk.com', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3400>: Failed to resolve 'v.2080kk.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://v.2080kk.com/home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=: HTTPSConnectionPool(host='v.2080kk.com', port=443): Max retries exceeded with url: /home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2770>: Failed to resolve 'v.2080kk.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://freejx.rx88.top:1234/?url=: HTTPSConnectionPool(host='freejx.rx88.top', port=1234): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2b30>: Failed to resolve 'freejx.rx88.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://freejx.rx88.top:1234/?url=: HTTPSConnectionPool(host='freejx.rx88.top', port=1234): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2320>: Failed to resolve 'freejx.rx88.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://freejx.rx88.top:1234/?url=: HTTPSConnectionPool(host='freejx.rx88.top', port=1234): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5faf0>: Failed to resolve 'freejx.rx88.top' ([Errno -5] No address associated with hostname)"))
测速失败 https://jx.iztyy.com/svip/?url=: HTTPSConnectionPool(host='jx.iztyy.com', port=443): Max retries exceeded with url: /svip/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
测速失败 https://jx.iztyy.com/svip/?url=: HTTPSConnectionPool(host='jx.iztyy.com', port=443): Max retries exceeded with url: /svip/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
测速失败 https://jx.iztyy.com/svip/?url=: HTTPSConnectionPool(host='jx.iztyy.com', port=443): Max retries exceeded with url: /svip/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
测速失败 https://m2090.com/?url=: HTTPSConnectionPool(host='m2090.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://m2090.com/?url=: HTTPSConnectionPool(host='m2090.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://m2090.com/?url=: HTTPSConnectionPool(host='m2090.com', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1540>: Failed to establish a new connection: [Errno 111] Connection refused'))
测速失败 https://go.yh0523.cn/y.cy?url=: HTTPSConnectionPool(host='go.yh0523.cn', port=443): Max retries exceeded with url: /y.cy?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3610>: Failed to resolve 'go.yh0523.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://go.yh0523.cn/y.cy?url=: HTTPSConnectionPool(host='go.yh0523.cn', port=443): Max retries exceeded with url: /y.cy?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0730>: Failed to resolve 'go.yh0523.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://go.yh0523.cn/y.cy?url=: HTTPSConnectionPool(host='go.yh0523.cn', port=443): Max retries exceeded with url: /y.cy?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1d50>: Failed to resolve 'go.yh0523.cn' ([Errno -5] No address associated with hostname)"))
测速失败 https://jx.bozrc.com:4433/player/?url=: HTTPSConnectionPool(host='jx.bozrc.com', port=4433): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2d10>, 'Connection to jx.bozrc.com timed out. (connect timeout=5)'))
测速失败 https://jx.bozrc.com:4433/player/?url=: HTTPSConnectionPool(host='jx.bozrc.com', port=4433): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5ca90>, 'Connection to jx.bozrc.com timed out. (connect timeout=5)'))
测速失败 https://jx.bozrc.com:4433/player/?url=: HTTPSConnectionPool(host='jx.bozrc.com', port=4433): Max retries exceeded with url: /player/?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2a70>, 'Connection to jx.bozrc.com timed out. (connect timeout=5)'))
测速失败 https://js.52jx.top:2525/?url=: HTTPSConnectionPool(host='js.52jx.top', port=2525): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2230>: Failed to resolve 'js.52jx.top' ([Errno -2] Name or service not known)"))
测速失败 https://js.52jx.top:2525/?url=: HTTPSConnectionPool(host='js.52jx.top', port=2525): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1db0>: Failed to resolve 'js.52jx.top' ([Errno -2] Name or service not known)"))
测速失败 https://js.52jx.top:2525/?url=: HTTPSConnectionPool(host='js.52jx.top', port=2525): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0b20>: Failed to resolve 'js.52jx.top' ([Errno -2] Name or service not known)"))
测速失败 https://sb.5gseo.net/?url=: HTTPSConnectionPool(host='sb.5gseo.net', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf39a0>: Failed to resolve 'sb.5gseo.net' ([Errno -5] No address associated with hostname)"))
测速失败 https://sb.5gseo.net/?url=: HTTPSConnectionPool(host='sb.5gseo.net', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5f1f0>: Failed to resolve 'sb.5gseo.net' ([Errno -5] No address associated with hostname)"))
测速失败 https://sb.5gseo.net/?url=: HTTPSConnectionPool(host='sb.5gseo.net', port=443): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0760>: Failed to resolve 'sb.5gseo.net' ([Errno -5] No address associated with hostname)"))
测速失败 https://jx.bynote.top/API.php?url=: HTTPSConnectionPool(host='jx.bynote.top', port=443): Max retries exceeded with url: /API.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jx.bynote.top'. (_ssl.c:1007)")))
测速失败 https://jx.bynote.top/API.php?url=: HTTPSConnectionPool(host='jx.bynote.top', port=443): Max retries exceeded with url: /API.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jx.bynote.top'. (_ssl.c:1007)")))
测速失败 https://jx.bynote.top/API.php?url=: HTTPSConnectionPool(host='jx.bynote.top', port=443): Max retries exceeded with url: /API.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jx.bynote.top'. (_ssl.c:1007)")))
测速失败 http://27.124.4.42:4567/jhjson/ceshi.php?url=: HTTPConnectionPool(host='27.124.4.42', port=4567): Max retries exceeded with url: /jhjson/ceshi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ebf3070>, 'Connection to 27.124.4.42 timed out. (connect timeout=5)'))
测速失败 http://27.124.4.42:4567/jhjson/ceshi.php?url=: HTTPConnectionPool(host='27.124.4.42', port=4567): Max retries exceeded with url: /jhjson/ceshi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ebf1990>, 'Connection to 27.124.4.42 timed out. (connect timeout=5)'))
测速失败 http://27.124.4.42:4567/jhjson/ceshi.php?url=: HTTPConnectionPool(host='27.124.4.42', port=4567): Max retries exceeded with url: /jhjson/ceshi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0250>, 'Connection to 27.124.4.42 timed out. (connect timeout=5)'))
测速失败 https://vip.bljiex.com/?v=: HTTPSConnectionPool(host='vip.bljiex.com', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2140>: Failed to resolve 'vip.bljiex.com' ([Errno -2] Name or service not known)"))
测速失败 https://vip.bljiex.com/?v=: HTTPSConnectionPool(host='vip.bljiex.com', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2d70>: Failed to resolve 'vip.bljiex.com' ([Errno -2] Name or service not known)"))
测速失败 https://vip.bljiex.com/?v=: HTTPSConnectionPool(host='vip.bljiex.com', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3580>: Failed to resolve 'vip.bljiex.com' ([Errno -2] Name or service not known)"))
测速失败 https://vip.laobandq.com/jiexi.php?url=: HTTPSConnectionPool(host='vip.laobandq.com', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2350>: Failed to resolve 'vip.laobandq.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://vip.laobandq.com/jiexi.php?url=: HTTPSConnectionPool(host='vip.laobandq.com', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf31c0>: Failed to resolve 'vip.laobandq.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://vip.laobandq.com/jiexi.php?url=: HTTPSConnectionPool(host='vip.laobandq.com', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf31f0>: Failed to resolve 'vip.laobandq.com' ([Errno -5] No address associated with hostname)"))
测速失败 https://www.pangujiexi.cc/jiexi.php?url=: HTTPSConnectionPool(host='www.pangujiexi.cc', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.pangujiexi.cc'. (_ssl.c:1007)")))
测速失败 https://www.pangujiexi.cc/jiexi.php?url=: HTTPSConnectionPool(host='www.pangujiexi.cc', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.pangujiexi.cc'. (_ssl.c:1007)")))
测速失败 https://www.pangujiexi.cc/jiexi.php?url=: HTTPSConnectionPool(host='www.pangujiexi.cc', port=443): Max retries exceeded with url: /jiexi.php?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.pangujiexi.cc'. (_ssl.c:1007)")))
测速失败 https://jx.blbo.cc:4433/?url=: HTTPSConnectionPool(host='jx.blbo.cc', port=4433): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ed5fdc0>, 'Connection to jx.blbo.cc timed out. (connect timeout=5)'))
测速失败 https://jx.blbo.cc:4433/?url=: HTTPSConnectionPool(host='jx.blbo.cc', port=4433): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0d60>, 'Connection to jx.blbo.cc timed out. (connect timeout=5)'))
测速失败 https://jx.blbo.cc:4433/?url=: HTTPSConnectionPool(host='jx.blbo.cc', port=4433): Max retries exceeded with url: /?url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf2590>, 'Connection to jx.blbo.cc timed out. (connect timeout=5)'))
测速失败 https://jx.rdhk.net/?v=: HTTPSConnectionPool(host='jx.rdhk.net', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf0580>: Failed to resolve 'jx.rdhk.net' ([Errno -2] Name or service not known)"))
测速失败 https://jx.rdhk.net/?v=: HTTPSConnectionPool(host='jx.rdhk.net', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf1240>: Failed to resolve 'jx.rdhk.net' ([Errno -2] Name or service not known)"))
测速失败 https://jx.rdhk.net/?v=: HTTPSConnectionPool(host='jx.rdhk.net', port=443): Max retries exceeded with url: /?v=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b8ebf3eb0>: Failed to resolve 'jx.rdhk.net' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf3f10>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf3250>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf0550>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf2d70>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ebf11e0>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
测速失败 http://xn--ihqu10cn4c.xn--z7x900a.live/jx.php?id=2&url=: HTTPConnectionPool(host='xn--ihqu10cn4c.xn--z7x900a.live', port=80): Max retries exceeded with url: /jx.php?id=2&url=https://v.qq.com/x/cover/mzc00200jterl3u.html (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3b8ed5f280>: Failed to resolve 'xn--ihqu10cn4c.xn--z7x900a.live' ([Errno -2] Name or service not known)"))
